### ISSUE TITLE
Not performing as well as load-grunt-tasks

### ISSUE THREAD

**Issue by Scotchester** [shootaroo/jit-grunt#30]
I'm implementing jit-grunt on a project I just started, and performance with jit-grunt (v0.9.1) is significantly slower than [load-grunt-tasks](https://github.com/sindresorhus/load-grunt-tasks) (v1.0.0)

load-grunt-tasks:
![screen shot 2015-03-25 at 11 56 25](https://cloud.githubusercontent.com/assets/1044670/6830203/b4c2c94e-d2ee-11e4-8c0d-3cbd07069889.png)

jit-grunt:
![screen shot 2015-03-25 at 11 55 51](https://cloud.githubusercontent.com/assets/1044670/6831117/adb834e4-d2f4-11e4-801d-4280a543da53.png)

This is executing a multi-task alias, but it does not include all Grunt tasks in this project, so in theory, load-grunt-tasks is loading tasks that aren't being used and is still half a second faster than jit-grunt. Is it just that much faster at loading tasks? Any idea what could be going on?

**Comment by shootaroo** [comment]
Is the order of `load-grunt-tasks` and `time-grunt` as follows?
```js
require('load-grunt-tasks')(grunt);
require('time-grunt')(grunt);
```
In this case time by aaa is not measured. Please reverse it.
```js
require('time-grunt')(grunt);
require('load-grunt-tasks')(grunt);
```

**Comment by Scotchester** [comment]
Wow, you totally guessed it. I was requiring load-grunt-tasks before time-grunt. Sorry for wasting your time, and thanks again for the great plugin :)
