### ISSUE TITLE
Task names prepended with underscores not supported

### ISSUE THREAD

**Issue by dotherightthing** [shootaroo/jit-grunt#31]
This is a bit of an edge case, but

In this scenario:

     grunt.registerTask("_taskgroup1", [ "task1", "task2", "task3"]);
     grunt.registerTask("taskgroup2", ["_taskgroup1"]);

I get this error:

    jit-grunt: Plugin for the "styleguide" task not found.
    If you have installed the plugin already, please setting the static mapping.
    See https://github.com/shootaroo/jit-grunt#static-mappings

    Warning: Task "styleguide" failed. Use --force to continue.

Thanks,
Dan

**Comment by shootaroo** [comment]
This error is `grunt-styleguide` plugin not found.
Is it really caused by task names prepended with underscores?

**Comment by dotherightthing** [comment]
Hi again,

I've just struck this problem again, so I'll have another go at describing it :)

I've created a custom task which sets a configuration option for another task. It's not packaged as a Grunt plugin but is registered as a task:

         grunt.registerTask("TASK1_CONFIG", function() {
             grunt.config.set('TASK1.OPTION', VALUE);
         });

I want to call `TASK1_CONFIG` from `TASK2`, which also runs `TASK1` proper. I do this by adding the custom task's name to `TASK2`'s task array:

         grunt.registerTask("TASK2", [
             "TASK1_CONFIG",
             "TASK1"
         ]);

When I run `grunt TASK2` I get the error `Plugin for the "TASK1_CONFIG" task not found`.

Thanks,
Dan

**Comment by dotherightthing** [comment]
I now have this working using this custom task pattern: https://quickleft.com/blog/grunt-js-custom-tasks/
