### ISSUE TITLE
"grunt help" task not found

### ISSUE THREAD

**Issue by cRoCx** [shootaroo/jit-grunt#32]
Hi,
the task `grunt help` doesn't work anymore after switching to `jit-grunt`.
I guess other default grunt tasks might be affected as well, since `jit-grunt` is not looking for `grunt` itself in the plugin directory, not even when setting:
`require('jit-grunt')(grunt, {
			help: 'grunt'
		});`
in the `Gruntfile.js`

**Comment by shootaroo** [comment]
`help` task? Is it not `--help` option?
Grunt does not have a tasks of default.

**Comment by cRoCx** [comment]
Something made me strongly believe, that the `help` option is a task as well, instead of an option. Sorry. My fault. Thanks for your reply.
