### ISSUE TITLE
jit-grunt: Plugin for the "express-keepalive" task not found.

### ISSUE THREAD

**Issue by ndjordjevic** [shootaroo/jit-grunt#34]
I've got this in my Gruntfile.js:
```grunt.registerTask('express-keepalive ', 'Keep grunt running', function () {
   this.async();
  });```

And getting this warning and build gets failed:
```jit-grunt: Plugin for the "express-keepalive" task not found.```

No idea what needs to be done to overcome this.

Thanks

**Comment by ndjordjevic** [comment]
So, there was a trailing space in task name ('express-keepalive '). Removing this solved the problem. Maybe jit-grunt should tream leading and trailing spaces before process the task?

**Comment by shootaroo** [comment]
It's not jit-grunt problem. It's specification of grunt.
