### ISSUE TITLE
Absolute paths do not work correctly with pluginsRoot 

### ISSUE THREAD

**Issue by schmod** [shootaroo/jit-grunt#40]
The current behavior of `pluginsRoot` is somewhat confusing, and does not work correctly with absolute paths.

# Example 1

In this case, my working directory is `/home/schmod/myProject`, and I've set `pluginsRoot` to be `/home/schmod/myProject/plugins`.  In this case, jit-grunt tries to look for plugins in:

* `/home/schmod/myProject/home/schmod/myProject/plugins`
* `/home/schmod/home/schmod/myProject/plugins`
* `/home/home/schmod/myProject/plugins`
* `/home/schmod/myProject/plugins`

Admittedly, jit-grunt **will** find the plugin on the last step of this simple example, but we are unable to take advantage of any of the normal "findUp" logic that `jit-grunt` supposedly supports (ie. if my plugin is actually in `/home/schomd/myProject`).  

Given the fact that NPM@3 can produce very....interesting hierarchies of `node_modules` trees, it's pretty important for "findUp" to work.

# Example 2

In this example, I'm not going to use an absolute path, but will demonstrate how jit-grunt's  `pluginsRoot` option doesn't appear to be particularly useful in practice:

If my working directory is `/home/schmod/myProject/node_modules/subProject`, and I set `pluginsRoot: 'other/dir', jit-grunt will try to look for plugins in:

* `/home/schmod/myProject/node_modules/subProject/other/dir`
* `/home/schmod/myProject/node_modules/other/dir`
* `/home/schmod/myProject/other/dir`
* `/home/schmod/other/dir`
* `/home/other/dir`
* `/other/dir`

While I understand what's going on here, I'm not sure that this is the behavior that most users will expect or desire -- it's akin to saying "I've set up npm to install packages into a folder that is named something other than `node_modules`" -- it's possible, but exceedingly rare.

In this scenario, I would ideally expect jit-grunt to look for plugins in:

* `/home/schmod/myProject/node_modules/subProject/other/dir`
* `/home/schmod/myProject/node_modules/subProject/other`
* `/home/schmod/myProject/node_modules/subProject`
* `/home/schmod/myProject/node_modules`
* `/home/schmod/myProject`
* `/home/schmod`
* `/home`
* `/`

# Example 3

This is my actual use-case.  

In this scenario, my working directory is `/home/schmod/myProject`, but some of my grunt plugins are actually being provided by a submodule located in `/home/schmod/myProject/node_modules/subProject`.  

In this scenario, depending on the requirements for `myProject` and `subProject`, NPM@3 will either install my grunt plugins in `/home/schmod/myProject/node_modules` OR `/home/schmod/myProject/node_modules/subProject/node_modules`.  The current set of configuration options does not allow me to ask jit-grunt to "start searching in `./node_modules/subProject/node_modules` and traverse upwards from there."

Examples 1 and 2 were derived from my attempts to utilize jit-grunt's current functionality to accommodate this use-case.  

---

# Proposed Solution

I suspect that most users will not want/need to set the `pluginsRoot` option, but might want to set a `cwd` parameter that jit-grunt can use to resolve all paths against, as a "starting" point for the findUp algorithm.

In Example 3 above, I would set `cwd: './node_modules/subProject'`, and leave `pluginsRoot` with its default value of `'node_modules'`:

```js
require('jit-grunt')(grunt)({
  cwd: path.join(process.cwd(), 'node_modules', 'subProject'), // or path.dirname(require.resolve('subProject'))
  pluginsRoot: 'node_modules'
});
```
From there, jit-grunt would traverse my filesystem as follows:

* `/home/schmod/myProject/node_modules/subProject/node_modules`
* `/home/schmod/myProject/node_modules/node_modules`
* `/home/schmod/myProject/node_modules/`
* `/home/schmod/node_modules/`
* `/home/node_modules`
* `/node_modules`

This still isn't ideal, because we're searching a few clearly-nonsensical paths, _but_ we're also a lot less likely to "miss" a plugin.

Additionally, some users might want the option to specify multiple search paths.

**Comment by schmod** [comment]
(Note that this merges cleanly into v0.9.1, but shouldn't be too difficult to adapt to the master branch)

**Comment by shootaroo** [comment]
Thanks!
