### ISSUE TITLE
Importing a grunt-lib that has multiple tasks in tasks folder.

### ISSUE THREAD

**Issue by oller** [shootaroo/jit-grunt#45]
I'm trying to use [grunt-webpack](https://github.com/webpack/grunt-webpack) with jit-grunt.

The grunt-webpack has 2 tasks:
- webpack
- webpack-dev-server

The `grunt-webpack` task loads automatically, imported succesfully by jit, however i'm having trouble importing the second task: `webpack-dev-server`.

``` js
    // Automatically load required grunt tasks
    require("jit-grunt")(grunt, {
        useminPrepare: "grunt-usemin",
        webpackDevServer: "grunt-webpack/tasks/webpack-dev-server.js"
    });
```

Any idea what i'm doing wrong, i've not had this problem before importing with jit, but then I've never had to specify a complete path before. 

Any help appreciated. Cheers!

**Comment by craigts** [comment]
@oller I imagine you're not still waiting for an answer here, but for anyone else that comes along...
This is how you get the webpack-dev-server task properly set up:

```
    // Automatically load required grunt tasks
    require("jit-grunt")(grunt, {
      "webpack-dev-server": "grunt-webpack"
    });
```

**Comment by shootaroo** [comment]
Thanks @craigts
