### ISSUE TITLE
Add support for Grunt v1.x

### ISSUE THREAD

**Issue by niemyjski** [shootaroo/jit-grunt#46]
I get a npm warning when I target the latest versions of grunt.. Everything seems to still be working.

```
npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was installed.
```

**Comment by kyvour** [comment]
+1

**Comment by shootaroo** [comment]
Please use latest version.

**Comment by niemyjski** [comment]
@shootaroo I am using the latest version!  Please reopen this.

**Comment by shootaroo** [comment]
> ```
> npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was installed.
> ```

No, latest version is `0.10.0`.
